import"./assets/styles-C7u3ywtQ.js";import{a as n,i as a}from"./assets/vendor-C6gZL8dd.js";const y=1;async function C(){return(await n("https://dummyjson.com/products/category-list")).data}async function l(){const t=`https://dummyjson.com/products?limit=12&skip=${(y-1)*12}`;return(await n(t)).data.products}async function _(t){if(t==="all")return l();const o=`https://dummyjson.com/products/category/${t}?limit=12&skip=${(y-1)*12}`;return(await n(o)).data.products}async function $(t){const o=`https://dummyjson.com/products/${t}`;return(await n(o)).data}async function v(t){const o=`https://dummyjson.com/products/search?q=${t}&limit=12&skip=${(y-1)*12}`;return(await n(o)).data.products}const f={SELECTED_CATEGORY:"selected_category"};function S(t){localStorage.setItem(f.SELECTED_CATEGORY,t)}function h(){return localStorage.getItem(f.SELECTED_CATEGORY)||"all"}function P(t){const o=h();t.map(s=>s.toLowerCase()).includes(o)||localStorage.setItem("selected_category","all");const r=["All","nobody",...t].map(s=>{const c=s.toLowerCase()===o.toLowerCase()?"categories__btn--active":"";return`<li class="categories__item" data-category="${s.toLowerCase()}">
   <button class="categories__btn ${c}" type="button">${s}</button>
 </li>`}).join("");e.categories.innerHTML=r,e.categories.addEventListener("click",k)}function i(t){if(e.products.innerHTML="",!t||t.length===0){e.notFoundBlock&&e.notFoundBlock.classList.add("not-found--visible");return}e.notFoundBlock&&e.notFoundBlock.classList.remove("not-found--visible");const o=t.map(r=>{const{id:s,title:c,brand:d,category:u,price:p,description:m,images:L}=r,b=L?.[0]||"https://via.placeholder.com/150";return`<li class="products__item" data-id="${s}">
    <img class="products__image" src="${b}" alt="${m}"/>
    <p class="products__title">${c}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${d}</span></p>
    <p class="products__category">Category:${u} </p>
    <p class="products__price">Price: ${p}</p>
 </li>`}).join("");e.products.insertAdjacentHTML("beforeend",o)}async function k(t){const o=t.target.closest(".categories__btn");if(!o)return;e.categories.querySelectorAll(".categories__btn").forEach(c=>{c.classList.remove("categories__btn--active")}),o.classList.add("categories__btn--active");const s=o.textContent.trim().toLowerCase();S(s);try{const c=s==="all"?await l():await _(s);i(c)}catch(c){console.error(`Error fetching products for ${s}:`,c),a.error({title:"Error",message:"Failed to fetch products. Please try again later.",position:"topRight"})}}async function w(t){const o=t.target.closest(".products__item");if(!o)return;const r=o.dataset.id;try{const s=await $(r);B(s)}catch(s){a.error({title:"Error",message:"Failed to fetch product details. Please try again later.",position:"topRight"}),console.error(`Error fetching product with ID ${r}:`,s)}}function B(t){if(!e.modalProduct)return;const{images:o,title:r,description:s,brand:c,category:d,price:u,shippingInformation:p,returnPolicy:m}=t;e.modalProduct.innerHTML=`
    <img class="modal-product__img" src="${o?.[0]||"https://via.placeholder.com/150"}" alt="${r}" />
    <div class="modal-product__content">
      <p class="modal-product__title">${r}</p>
      <ul class="modal-product__tags">
        <li>Brand: ${c}</li>
        <li>Category: ${d}</li>
      </ul>
      <p class="modal-product__description">${s}</p>
      <p class="modal-product__shipping-information">Shipping: ${p||"N/A"}</p>
      <p class="modal-product__return-policy">Return Policy: ${m||"N/A"}</p>
      <p class="modal-product__price">Price: $${u}</p>
      <button class="modal-product__buy-btn" type="button">Buy</button>
    </div>`,e.modal.classList.add("modal--is-open"),E()}function E(){e.modal.addEventListener("click",t=>{(t.target===e.modal||t.target.classList.contains("modal-product__buy-btn"))&&g()}),document.addEventListener("keydown",t=>{t.key==="Escape"&&g()}),e.modalCloseBtn.addEventListener("click",g)}function g(){e.modal.classList.remove("modal--is-open"),e.modalProduct.innerHTML="",e.modal.removeEventListener("click",E)}async function F(t){t.preventDefault();const o=t.target.elements.searchValue.value.trim();if(!o){try{const r=await l();i(r)}catch(r){a.error({title:"Error",message:"Failed to fetch products. Please try again later.",position:"topRight"}),console.error("Error fetching home products:",r)}e.searchForm.reset(),e.notFoundBlock.classList.remove("not-found--visible");return}try{const r=await v(o);r.length===0?(e.notFoundBlock.classList.add("not-found--visible"),e.products.innerHTML=""):(e.notFoundBlock.classList.remove("not-found--visible"),i(r))}catch(r){a.error({title:"Error",message:"Failed to fetch products. Please try again later.",position:"topRight"}),console.error("Error fetching products by search:",r)}e.searchForm.reset()}const e={form:document.querySelector(".search-form"),categories:document.querySelector(".categories"),products:document.querySelector(".products"),notFoundBlock:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),searchFormClearBtn:document.querySelector(".search-form__btn-clear")};try{const t=await C();P(t);const o=h(),r=o==="all"?await l():await _(o);i(r)}catch(t){a.error({title:"Error",message:"Failed to fetch categories or products. Please try again later.",position:"topRight"}),console.error("Error fetching categories or products:",t)}e.products.addEventListener("click",w);e.searchForm.addEventListener("submit",F);
//# sourceMappingURL=index.js.map
